### ISSUE TITLE
doesn't preview text prompt

### ISSUE THREAD

**Issue by davoodice** [smthemex/ComfyUI_Pic2Story#4]
HI
it doesn't preview text prompt.
![image](https://github.com/user-attachments/assets/ae6738bd-18ac-4a14-ba81-be2006e8fda4)

**Comment by smthemex** [comment]
You need to add a“ description of this image” or other similar words in the prompt bar

**Comment by davoodice** [comment]
Actually It does it automatically and everything works fine. Just it doesn't show the preview text. I found this is a update text problem but not sure if it happens in show text node or pic2story one. Anyway when I drag the generated image inside comfyUI, I can see generated prompt in show text node.

**Comment by smthemex** [comment]
It can be used without prompts, and with prompt conditional processing, the hit rate is higher
