### ISSUE TITLE
Error after Comfy Update

### ISSUE THREAD

**Issue by murphylanga** [smthemex/ComfyUI_Pic2Story#6]
When loading the graph, the following node types were not found: 
Pic2Story Nodes that have failed to load will show as red on the graph.

**Comment by smthemex** [comment]
please update ，using new workflow.

**Comment by murphylanga** [comment]
Thank you for the info! I could have thought of that myself, just get the nodes again. But sometimes you're at a loss. Thank you again :-)

**Comment by murphylanga** [comment]
Works perfectly
